package me.dingtou.domain;

public class FundGroupDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_group_detail.fund_group_id
     *
     * @mbg.generated Sun Jun 18 17:09:13 CST 2017
     */
    private Integer fundGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_group_detail.fund_code
     *
     * @mbg.generated Sun Jun 18 17:09:13 CST 2017
     */
    private String fundCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_group_detail.order_rate
     *
     * @mbg.generated Sun Jun 18 17:09:13 CST 2017
     */
    private Integer orderRate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_group_detail.fund_group_id
     *
     * @return the value of fund_group_detail.fund_group_id
     *
     * @mbg.generated Sun Jun 18 17:09:13 CST 2017
     */
    public Integer getFundGroupId() {
        return fundGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_group_detail.fund_group_id
     *
     * @param fundGroupId the value for fund_group_detail.fund_group_id
     *
     * @mbg.generated Sun Jun 18 17:09:13 CST 2017
     */
    public void setFundGroupId(Integer fundGroupId) {
        this.fundGroupId = fundGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_group_detail.fund_code
     *
     * @return the value of fund_group_detail.fund_code
     *
     * @mbg.generated Sun Jun 18 17:09:13 CST 2017
     */
    public String getFundCode() {
        return fundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_group_detail.fund_code
     *
     * @param fundCode the value for fund_group_detail.fund_code
     *
     * @mbg.generated Sun Jun 18 17:09:13 CST 2017
     */
    public void setFundCode(String fundCode) {
        this.fundCode = fundCode == null ? null : fundCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_group_detail.order_rate
     *
     * @return the value of fund_group_detail.order_rate
     *
     * @mbg.generated Sun Jun 18 17:09:13 CST 2017
     */
    public Integer getOrderRate() {
        return orderRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_group_detail.order_rate
     *
     * @param orderRate the value for fund_group_detail.order_rate
     *
     * @mbg.generated Sun Jun 18 17:09:13 CST 2017
     */
    public void setOrderRate(Integer orderRate) {
        this.orderRate = orderRate;
    }
}