package me.dingtou.domain;

import java.util.ArrayList;
import java.util.List;

public class FundGroupDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fund_group_detail
     *
     * @mbg.generated Sun Jun 18 17:09:13 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fund_group_detail
     *
     * @mbg.generated Sun Jun 18 17:09:13 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fund_group_detail
     *
     * @mbg.generated Sun Jun 18 17:09:13 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_group_detail
     *
     * @mbg.generated Sun Jun 18 17:09:13 CST 2017
     */
    public FundGroupDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_group_detail
     *
     * @mbg.generated Sun Jun 18 17:09:13 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_group_detail
     *
     * @mbg.generated Sun Jun 18 17:09:13 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_group_detail
     *
     * @mbg.generated Sun Jun 18 17:09:13 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_group_detail
     *
     * @mbg.generated Sun Jun 18 17:09:13 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_group_detail
     *
     * @mbg.generated Sun Jun 18 17:09:13 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_group_detail
     *
     * @mbg.generated Sun Jun 18 17:09:13 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_group_detail
     *
     * @mbg.generated Sun Jun 18 17:09:13 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_group_detail
     *
     * @mbg.generated Sun Jun 18 17:09:13 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_group_detail
     *
     * @mbg.generated Sun Jun 18 17:09:13 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_group_detail
     *
     * @mbg.generated Sun Jun 18 17:09:13 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fund_group_detail
     *
     * @mbg.generated Sun Jun 18 17:09:13 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFundGroupIdIsNull() {
            addCriterion("fund_group_id is null");
            return (Criteria) this;
        }

        public Criteria andFundGroupIdIsNotNull() {
            addCriterion("fund_group_id is not null");
            return (Criteria) this;
        }

        public Criteria andFundGroupIdEqualTo(Integer value) {
            addCriterion("fund_group_id =", value, "fundGroupId");
            return (Criteria) this;
        }

        public Criteria andFundGroupIdNotEqualTo(Integer value) {
            addCriterion("fund_group_id <>", value, "fundGroupId");
            return (Criteria) this;
        }

        public Criteria andFundGroupIdGreaterThan(Integer value) {
            addCriterion("fund_group_id >", value, "fundGroupId");
            return (Criteria) this;
        }

        public Criteria andFundGroupIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("fund_group_id >=", value, "fundGroupId");
            return (Criteria) this;
        }

        public Criteria andFundGroupIdLessThan(Integer value) {
            addCriterion("fund_group_id <", value, "fundGroupId");
            return (Criteria) this;
        }

        public Criteria andFundGroupIdLessThanOrEqualTo(Integer value) {
            addCriterion("fund_group_id <=", value, "fundGroupId");
            return (Criteria) this;
        }

        public Criteria andFundGroupIdIn(List<Integer> values) {
            addCriterion("fund_group_id in", values, "fundGroupId");
            return (Criteria) this;
        }

        public Criteria andFundGroupIdNotIn(List<Integer> values) {
            addCriterion("fund_group_id not in", values, "fundGroupId");
            return (Criteria) this;
        }

        public Criteria andFundGroupIdBetween(Integer value1, Integer value2) {
            addCriterion("fund_group_id between", value1, value2, "fundGroupId");
            return (Criteria) this;
        }

        public Criteria andFundGroupIdNotBetween(Integer value1, Integer value2) {
            addCriterion("fund_group_id not between", value1, value2, "fundGroupId");
            return (Criteria) this;
        }

        public Criteria andFundCodeIsNull() {
            addCriterion("fund_code is null");
            return (Criteria) this;
        }

        public Criteria andFundCodeIsNotNull() {
            addCriterion("fund_code is not null");
            return (Criteria) this;
        }

        public Criteria andFundCodeEqualTo(String value) {
            addCriterion("fund_code =", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeNotEqualTo(String value) {
            addCriterion("fund_code <>", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeGreaterThan(String value) {
            addCriterion("fund_code >", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeGreaterThanOrEqualTo(String value) {
            addCriterion("fund_code >=", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeLessThan(String value) {
            addCriterion("fund_code <", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeLessThanOrEqualTo(String value) {
            addCriterion("fund_code <=", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeLike(String value) {
            addCriterion("fund_code like", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeNotLike(String value) {
            addCriterion("fund_code not like", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeIn(List<String> values) {
            addCriterion("fund_code in", values, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeNotIn(List<String> values) {
            addCriterion("fund_code not in", values, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeBetween(String value1, String value2) {
            addCriterion("fund_code between", value1, value2, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeNotBetween(String value1, String value2) {
            addCriterion("fund_code not between", value1, value2, "fundCode");
            return (Criteria) this;
        }

        public Criteria andOrderRateIsNull() {
            addCriterion("order_rate is null");
            return (Criteria) this;
        }

        public Criteria andOrderRateIsNotNull() {
            addCriterion("order_rate is not null");
            return (Criteria) this;
        }

        public Criteria andOrderRateEqualTo(Integer value) {
            addCriterion("order_rate =", value, "orderRate");
            return (Criteria) this;
        }

        public Criteria andOrderRateNotEqualTo(Integer value) {
            addCriterion("order_rate <>", value, "orderRate");
            return (Criteria) this;
        }

        public Criteria andOrderRateGreaterThan(Integer value) {
            addCriterion("order_rate >", value, "orderRate");
            return (Criteria) this;
        }

        public Criteria andOrderRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_rate >=", value, "orderRate");
            return (Criteria) this;
        }

        public Criteria andOrderRateLessThan(Integer value) {
            addCriterion("order_rate <", value, "orderRate");
            return (Criteria) this;
        }

        public Criteria andOrderRateLessThanOrEqualTo(Integer value) {
            addCriterion("order_rate <=", value, "orderRate");
            return (Criteria) this;
        }

        public Criteria andOrderRateIn(List<Integer> values) {
            addCriterion("order_rate in", values, "orderRate");
            return (Criteria) this;
        }

        public Criteria andOrderRateNotIn(List<Integer> values) {
            addCriterion("order_rate not in", values, "orderRate");
            return (Criteria) this;
        }

        public Criteria andOrderRateBetween(Integer value1, Integer value2) {
            addCriterion("order_rate between", value1, value2, "orderRate");
            return (Criteria) this;
        }

        public Criteria andOrderRateNotBetween(Integer value1, Integer value2) {
            addCriterion("order_rate not between", value1, value2, "orderRate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fund_group_detail
     *
     * @mbg.generated do_not_delete_during_merge Sun Jun 18 17:09:13 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fund_group_detail
     *
     * @mbg.generated Sun Jun 18 17:09:13 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}