package me.dingtou.domain;

import java.util.ArrayList;
import java.util.List;

public class FundInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    public FundInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFundCodeIsNull() {
            addCriterion("fund_code is null");
            return (Criteria) this;
        }

        public Criteria andFundCodeIsNotNull() {
            addCriterion("fund_code is not null");
            return (Criteria) this;
        }

        public Criteria andFundCodeEqualTo(String value) {
            addCriterion("fund_code =", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeNotEqualTo(String value) {
            addCriterion("fund_code <>", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeGreaterThan(String value) {
            addCriterion("fund_code >", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeGreaterThanOrEqualTo(String value) {
            addCriterion("fund_code >=", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeLessThan(String value) {
            addCriterion("fund_code <", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeLessThanOrEqualTo(String value) {
            addCriterion("fund_code <=", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeLike(String value) {
            addCriterion("fund_code like", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeNotLike(String value) {
            addCriterion("fund_code not like", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeIn(List<String> values) {
            addCriterion("fund_code in", values, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeNotIn(List<String> values) {
            addCriterion("fund_code not in", values, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeBetween(String value1, String value2) {
            addCriterion("fund_code between", value1, value2, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeNotBetween(String value1, String value2) {
            addCriterion("fund_code not between", value1, value2, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundNameIsNull() {
            addCriterion("fund_name is null");
            return (Criteria) this;
        }

        public Criteria andFundNameIsNotNull() {
            addCriterion("fund_name is not null");
            return (Criteria) this;
        }

        public Criteria andFundNameEqualTo(String value) {
            addCriterion("fund_name =", value, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameNotEqualTo(String value) {
            addCriterion("fund_name <>", value, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameGreaterThan(String value) {
            addCriterion("fund_name >", value, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameGreaterThanOrEqualTo(String value) {
            addCriterion("fund_name >=", value, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameLessThan(String value) {
            addCriterion("fund_name <", value, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameLessThanOrEqualTo(String value) {
            addCriterion("fund_name <=", value, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameLike(String value) {
            addCriterion("fund_name like", value, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameNotLike(String value) {
            addCriterion("fund_name not like", value, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameIn(List<String> values) {
            addCriterion("fund_name in", values, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameNotIn(List<String> values) {
            addCriterion("fund_name not in", values, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameBetween(String value1, String value2) {
            addCriterion("fund_name between", value1, value2, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameNotBetween(String value1, String value2) {
            addCriterion("fund_name not between", value1, value2, "fundName");
            return (Criteria) this;
        }

        public Criteria andBuyRateIsNull() {
            addCriterion("buy_rate is null");
            return (Criteria) this;
        }

        public Criteria andBuyRateIsNotNull() {
            addCriterion("buy_rate is not null");
            return (Criteria) this;
        }

        public Criteria andBuyRateEqualTo(String value) {
            addCriterion("buy_rate =", value, "buyRate");
            return (Criteria) this;
        }

        public Criteria andBuyRateNotEqualTo(String value) {
            addCriterion("buy_rate <>", value, "buyRate");
            return (Criteria) this;
        }

        public Criteria andBuyRateGreaterThan(String value) {
            addCriterion("buy_rate >", value, "buyRate");
            return (Criteria) this;
        }

        public Criteria andBuyRateGreaterThanOrEqualTo(String value) {
            addCriterion("buy_rate >=", value, "buyRate");
            return (Criteria) this;
        }

        public Criteria andBuyRateLessThan(String value) {
            addCriterion("buy_rate <", value, "buyRate");
            return (Criteria) this;
        }

        public Criteria andBuyRateLessThanOrEqualTo(String value) {
            addCriterion("buy_rate <=", value, "buyRate");
            return (Criteria) this;
        }

        public Criteria andBuyRateLike(String value) {
            addCriterion("buy_rate like", value, "buyRate");
            return (Criteria) this;
        }

        public Criteria andBuyRateNotLike(String value) {
            addCriterion("buy_rate not like", value, "buyRate");
            return (Criteria) this;
        }

        public Criteria andBuyRateIn(List<String> values) {
            addCriterion("buy_rate in", values, "buyRate");
            return (Criteria) this;
        }

        public Criteria andBuyRateNotIn(List<String> values) {
            addCriterion("buy_rate not in", values, "buyRate");
            return (Criteria) this;
        }

        public Criteria andBuyRateBetween(String value1, String value2) {
            addCriterion("buy_rate between", value1, value2, "buyRate");
            return (Criteria) this;
        }

        public Criteria andBuyRateNotBetween(String value1, String value2) {
            addCriterion("buy_rate not between", value1, value2, "buyRate");
            return (Criteria) this;
        }

        public Criteria andSellRateIsNull() {
            addCriterion("sell_rate is null");
            return (Criteria) this;
        }

        public Criteria andSellRateIsNotNull() {
            addCriterion("sell_rate is not null");
            return (Criteria) this;
        }

        public Criteria andSellRateEqualTo(String value) {
            addCriterion("sell_rate =", value, "sellRate");
            return (Criteria) this;
        }

        public Criteria andSellRateNotEqualTo(String value) {
            addCriterion("sell_rate <>", value, "sellRate");
            return (Criteria) this;
        }

        public Criteria andSellRateGreaterThan(String value) {
            addCriterion("sell_rate >", value, "sellRate");
            return (Criteria) this;
        }

        public Criteria andSellRateGreaterThanOrEqualTo(String value) {
            addCriterion("sell_rate >=", value, "sellRate");
            return (Criteria) this;
        }

        public Criteria andSellRateLessThan(String value) {
            addCriterion("sell_rate <", value, "sellRate");
            return (Criteria) this;
        }

        public Criteria andSellRateLessThanOrEqualTo(String value) {
            addCriterion("sell_rate <=", value, "sellRate");
            return (Criteria) this;
        }

        public Criteria andSellRateLike(String value) {
            addCriterion("sell_rate like", value, "sellRate");
            return (Criteria) this;
        }

        public Criteria andSellRateNotLike(String value) {
            addCriterion("sell_rate not like", value, "sellRate");
            return (Criteria) this;
        }

        public Criteria andSellRateIn(List<String> values) {
            addCriterion("sell_rate in", values, "sellRate");
            return (Criteria) this;
        }

        public Criteria andSellRateNotIn(List<String> values) {
            addCriterion("sell_rate not in", values, "sellRate");
            return (Criteria) this;
        }

        public Criteria andSellRateBetween(String value1, String value2) {
            addCriterion("sell_rate between", value1, value2, "sellRate");
            return (Criteria) this;
        }

        public Criteria andSellRateNotBetween(String value1, String value2) {
            addCriterion("sell_rate not between", value1, value2, "sellRate");
            return (Criteria) this;
        }

        public Criteria andRoundingModeIsNull() {
            addCriterion("rounding_mode is null");
            return (Criteria) this;
        }

        public Criteria andRoundingModeIsNotNull() {
            addCriterion("rounding_mode is not null");
            return (Criteria) this;
        }

        public Criteria andRoundingModeEqualTo(Integer value) {
            addCriterion("rounding_mode =", value, "roundingMode");
            return (Criteria) this;
        }

        public Criteria andRoundingModeNotEqualTo(Integer value) {
            addCriterion("rounding_mode <>", value, "roundingMode");
            return (Criteria) this;
        }

        public Criteria andRoundingModeGreaterThan(Integer value) {
            addCriterion("rounding_mode >", value, "roundingMode");
            return (Criteria) this;
        }

        public Criteria andRoundingModeGreaterThanOrEqualTo(Integer value) {
            addCriterion("rounding_mode >=", value, "roundingMode");
            return (Criteria) this;
        }

        public Criteria andRoundingModeLessThan(Integer value) {
            addCriterion("rounding_mode <", value, "roundingMode");
            return (Criteria) this;
        }

        public Criteria andRoundingModeLessThanOrEqualTo(Integer value) {
            addCriterion("rounding_mode <=", value, "roundingMode");
            return (Criteria) this;
        }

        public Criteria andRoundingModeIn(List<Integer> values) {
            addCriterion("rounding_mode in", values, "roundingMode");
            return (Criteria) this;
        }

        public Criteria andRoundingModeNotIn(List<Integer> values) {
            addCriterion("rounding_mode not in", values, "roundingMode");
            return (Criteria) this;
        }

        public Criteria andRoundingModeBetween(Integer value1, Integer value2) {
            addCriterion("rounding_mode between", value1, value2, "roundingMode");
            return (Criteria) this;
        }

        public Criteria andRoundingModeNotBetween(Integer value1, Integer value2) {
            addCriterion("rounding_mode not between", value1, value2, "roundingMode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fund_info
     *
     * @mbg.generated do_not_delete_during_merge Sun Aug 27 14:55:58 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}