package me.dingtou.domain;

public class FundInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.fund_code
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    private String fundCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.fund_name
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    private String fundName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.buy_rate
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    private String buyRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.sell_rate
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    private String sellRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.rounding_mode
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    private Integer roundingMode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.fund_code
     *
     * @return the value of fund_info.fund_code
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    public String getFundCode() {
        return fundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.fund_code
     *
     * @param fundCode the value for fund_info.fund_code
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    public void setFundCode(String fundCode) {
        this.fundCode = fundCode == null ? null : fundCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.fund_name
     *
     * @return the value of fund_info.fund_name
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    public String getFundName() {
        return fundName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.fund_name
     *
     * @param fundName the value for fund_info.fund_name
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    public void setFundName(String fundName) {
        this.fundName = fundName == null ? null : fundName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.buy_rate
     *
     * @return the value of fund_info.buy_rate
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    public String getBuyRate() {
        return buyRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.buy_rate
     *
     * @param buyRate the value for fund_info.buy_rate
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    public void setBuyRate(String buyRate) {
        this.buyRate = buyRate == null ? null : buyRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.sell_rate
     *
     * @return the value of fund_info.sell_rate
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    public String getSellRate() {
        return sellRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.sell_rate
     *
     * @param sellRate the value for fund_info.sell_rate
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    public void setSellRate(String sellRate) {
        this.sellRate = sellRate == null ? null : sellRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.rounding_mode
     *
     * @return the value of fund_info.rounding_mode
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    public Integer getRoundingMode() {
        return roundingMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.rounding_mode
     *
     * @param roundingMode the value for fund_info.rounding_mode
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    public void setRoundingMode(Integer roundingMode) {
        this.roundingMode = roundingMode;
    }
}