package me.dingtou.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TradeCalendarExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    public TradeCalendarExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFundGroupIdIsNull() {
            addCriterion("fund_group_id is null");
            return (Criteria) this;
        }

        public Criteria andFundGroupIdIsNotNull() {
            addCriterion("fund_group_id is not null");
            return (Criteria) this;
        }

        public Criteria andFundGroupIdEqualTo(Integer value) {
            addCriterion("fund_group_id =", value, "fundGroupId");
            return (Criteria) this;
        }

        public Criteria andFundGroupIdNotEqualTo(Integer value) {
            addCriterion("fund_group_id <>", value, "fundGroupId");
            return (Criteria) this;
        }

        public Criteria andFundGroupIdGreaterThan(Integer value) {
            addCriterion("fund_group_id >", value, "fundGroupId");
            return (Criteria) this;
        }

        public Criteria andFundGroupIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("fund_group_id >=", value, "fundGroupId");
            return (Criteria) this;
        }

        public Criteria andFundGroupIdLessThan(Integer value) {
            addCriterion("fund_group_id <", value, "fundGroupId");
            return (Criteria) this;
        }

        public Criteria andFundGroupIdLessThanOrEqualTo(Integer value) {
            addCriterion("fund_group_id <=", value, "fundGroupId");
            return (Criteria) this;
        }

        public Criteria andFundGroupIdIn(List<Integer> values) {
            addCriterion("fund_group_id in", values, "fundGroupId");
            return (Criteria) this;
        }

        public Criteria andFundGroupIdNotIn(List<Integer> values) {
            addCriterion("fund_group_id not in", values, "fundGroupId");
            return (Criteria) this;
        }

        public Criteria andFundGroupIdBetween(Integer value1, Integer value2) {
            addCriterion("fund_group_id between", value1, value2, "fundGroupId");
            return (Criteria) this;
        }

        public Criteria andFundGroupIdNotBetween(Integer value1, Integer value2) {
            addCriterion("fund_group_id not between", value1, value2, "fundGroupId");
            return (Criteria) this;
        }

        public Criteria andTradeDateIsNull() {
            addCriterion("trade_date is null");
            return (Criteria) this;
        }

        public Criteria andTradeDateIsNotNull() {
            addCriterion("trade_date is not null");
            return (Criteria) this;
        }

        public Criteria andTradeDateEqualTo(Date value) {
            addCriterion("trade_date =", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateNotEqualTo(Date value) {
            addCriterion("trade_date <>", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateGreaterThan(Date value) {
            addCriterion("trade_date >", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateGreaterThanOrEqualTo(Date value) {
            addCriterion("trade_date >=", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateLessThan(Date value) {
            addCriterion("trade_date <", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateLessThanOrEqualTo(Date value) {
            addCriterion("trade_date <=", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateIn(List<Date> values) {
            addCriterion("trade_date in", values, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateNotIn(List<Date> values) {
            addCriterion("trade_date not in", values, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateBetween(Date value1, Date value2) {
            addCriterion("trade_date between", value1, value2, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateNotBetween(Date value1, Date value2) {
            addCriterion("trade_date not between", value1, value2, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTargetPriceIsNull() {
            addCriterion("target_price is null");
            return (Criteria) this;
        }

        public Criteria andTargetPriceIsNotNull() {
            addCriterion("target_price is not null");
            return (Criteria) this;
        }

        public Criteria andTargetPriceEqualTo(Integer value) {
            addCriterion("target_price =", value, "targetPrice");
            return (Criteria) this;
        }

        public Criteria andTargetPriceNotEqualTo(Integer value) {
            addCriterion("target_price <>", value, "targetPrice");
            return (Criteria) this;
        }

        public Criteria andTargetPriceGreaterThan(Integer value) {
            addCriterion("target_price >", value, "targetPrice");
            return (Criteria) this;
        }

        public Criteria andTargetPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("target_price >=", value, "targetPrice");
            return (Criteria) this;
        }

        public Criteria andTargetPriceLessThan(Integer value) {
            addCriterion("target_price <", value, "targetPrice");
            return (Criteria) this;
        }

        public Criteria andTargetPriceLessThanOrEqualTo(Integer value) {
            addCriterion("target_price <=", value, "targetPrice");
            return (Criteria) this;
        }

        public Criteria andTargetPriceIn(List<Integer> values) {
            addCriterion("target_price in", values, "targetPrice");
            return (Criteria) this;
        }

        public Criteria andTargetPriceNotIn(List<Integer> values) {
            addCriterion("target_price not in", values, "targetPrice");
            return (Criteria) this;
        }

        public Criteria andTargetPriceBetween(Integer value1, Integer value2) {
            addCriterion("target_price between", value1, value2, "targetPrice");
            return (Criteria) this;
        }

        public Criteria andTargetPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("target_price not between", value1, value2, "targetPrice");
            return (Criteria) this;
        }

        public Criteria andTradeStatusIsNull() {
            addCriterion("trade_status is null");
            return (Criteria) this;
        }

        public Criteria andTradeStatusIsNotNull() {
            addCriterion("trade_status is not null");
            return (Criteria) this;
        }

        public Criteria andTradeStatusEqualTo(Integer value) {
            addCriterion("trade_status =", value, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusNotEqualTo(Integer value) {
            addCriterion("trade_status <>", value, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusGreaterThan(Integer value) {
            addCriterion("trade_status >", value, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("trade_status >=", value, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusLessThan(Integer value) {
            addCriterion("trade_status <", value, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusLessThanOrEqualTo(Integer value) {
            addCriterion("trade_status <=", value, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusIn(List<Integer> values) {
            addCriterion("trade_status in", values, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusNotIn(List<Integer> values) {
            addCriterion("trade_status not in", values, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusBetween(Integer value1, Integer value2) {
            addCriterion("trade_status between", value1, value2, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("trade_status not between", value1, value2, "tradeStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade_calendar
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 24 01:21:40 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}