package me.dingtou.mapper;

import me.dingtou.domain.FundInfo;
import me.dingtou.domain.FundInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface FundInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    long countByExample(FundInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    int deleteByExample(FundInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    int deleteByPrimaryKey(String fundCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    int insert(FundInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    int insertSelective(FundInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    List<FundInfo> selectByExample(FundInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    FundInfo selectByPrimaryKey(String fundCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") FundInfo record, @Param("example") FundInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    int updateByExample(@Param("record") FundInfo record, @Param("example") FundInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    int updateByPrimaryKeySelective(FundInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_info
     *
     * @mbg.generated Sun Aug 27 14:55:58 CST 2017
     */
    int updateByPrimaryKey(FundInfo record);
}