package me.dingtou.mapper;

import me.dingtou.domain.TradeCalendar;
import me.dingtou.domain.TradeCalendarExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface TradeCalendarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    long countByExample(TradeCalendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    int deleteByExample(TradeCalendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    int insert(TradeCalendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    int insertSelective(TradeCalendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    List<TradeCalendar> selectByExample(TradeCalendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    TradeCalendar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    int updateByExampleSelective(@Param("record") TradeCalendar record, @Param("example") TradeCalendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    int updateByExample(@Param("record") TradeCalendar record, @Param("example") TradeCalendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    int updateByPrimaryKeySelective(TradeCalendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_calendar
     *
     * @mbg.generated Sat Jun 24 01:21:40 CST 2017
     */
    int updateByPrimaryKey(TradeCalendar record);
}