package me.dingtou.mapper;

import java.util.List;
import me.dingtou.domain.UserFundGroup;
import me.dingtou.domain.UserFundGroupExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface UserFundGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_group
     *
     * @mbg.generated Sun Aug 09 23:40:03 CST 2020
     */
    long countByExample(UserFundGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_group
     *
     * @mbg.generated Sun Aug 09 23:40:03 CST 2020
     */
    int deleteByExample(UserFundGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_group
     *
     * @mbg.generated Sun Aug 09 23:40:03 CST 2020
     */
    int deleteByPrimaryKey(Integer fundGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_group
     *
     * @mbg.generated Sun Aug 09 23:40:03 CST 2020
     */
    int insert(UserFundGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_group
     *
     * @mbg.generated Sun Aug 09 23:40:03 CST 2020
     */
    int insertSelective(UserFundGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_group
     *
     * @mbg.generated Sun Aug 09 23:40:03 CST 2020
     */
    List<UserFundGroup> selectByExampleWithBLOBs(UserFundGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_group
     *
     * @mbg.generated Sun Aug 09 23:40:03 CST 2020
     */
    List<UserFundGroup> selectByExample(UserFundGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_group
     *
     * @mbg.generated Sun Aug 09 23:40:03 CST 2020
     */
    UserFundGroup selectByPrimaryKey(Integer fundGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_group
     *
     * @mbg.generated Sun Aug 09 23:40:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserFundGroup record, @Param("example") UserFundGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_group
     *
     * @mbg.generated Sun Aug 09 23:40:03 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") UserFundGroup record, @Param("example") UserFundGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_group
     *
     * @mbg.generated Sun Aug 09 23:40:03 CST 2020
     */
    int updateByExample(@Param("record") UserFundGroup record, @Param("example") UserFundGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_group
     *
     * @mbg.generated Sun Aug 09 23:40:03 CST 2020
     */
    int updateByPrimaryKeySelective(UserFundGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_group
     *
     * @mbg.generated Sun Aug 09 23:40:03 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(UserFundGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_group
     *
     * @mbg.generated Sun Aug 09 23:40:03 CST 2020
     */
    int updateByPrimaryKey(UserFundGroup record);
}