package me.dingtou.mapper;

import me.dingtou.domain.UserFundGroup;
import me.dingtou.domain.UserFundGroupExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface UserFundGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_group
     *
     * @mbg.generated Sun Jun 18 19:12:55 CST 2017
     */
    long countByExample(UserFundGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_group
     *
     * @mbg.generated Sun Jun 18 19:12:55 CST 2017
     */
    int deleteByExample(UserFundGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_group
     *
     * @mbg.generated Sun Jun 18 19:12:55 CST 2017
     */
    int deleteByPrimaryKey(Integer fundGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_group
     *
     * @mbg.generated Sun Jun 18 19:12:55 CST 2017
     */
    int insert(UserFundGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_group
     *
     * @mbg.generated Sun Jun 18 19:12:55 CST 2017
     */
    int insertSelective(UserFundGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_group
     *
     * @mbg.generated Sun Jun 18 19:12:55 CST 2017
     */
    List<UserFundGroup> selectByExample(UserFundGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_group
     *
     * @mbg.generated Sun Jun 18 19:12:55 CST 2017
     */
    UserFundGroup selectByPrimaryKey(Integer fundGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_group
     *
     * @mbg.generated Sun Jun 18 19:12:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserFundGroup record, @Param("example") UserFundGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_group
     *
     * @mbg.generated Sun Jun 18 19:12:55 CST 2017
     */
    int updateByExample(@Param("record") UserFundGroup record, @Param("example") UserFundGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_group
     *
     * @mbg.generated Sun Jun 18 19:12:55 CST 2017
     */
    int updateByPrimaryKeySelective(UserFundGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_group
     *
     * @mbg.generated Sun Jun 18 19:12:55 CST 2017
     */
    int updateByPrimaryKey(UserFundGroup record);
}